export const GAME = {
    WIDTH: 1080,
    HEIGHT: 1920,
    BACKGROUND_SCROLL_SPEED: 1,
};

export const PLAYER = {
    SPEED: 8,
    MAX_HP: 3,
    INVULNERABILITY_DURATION: 2000,
    FIRE_RATE: 200,
    BULLET_SPEED: -800,
};

export const ENEMIES = {
    BASIC_SPEED: 150,
    BASIC_HP: 1,
    BASIC_FIRE_RATE: 2000,
    ELITE_SPEED: 200,
    ELITE_HP: 2,
    ELITE_FIRE_RATE: 1500,
    BULLET_SPEED: 400,
};

export const BOSSES = {
    HP_MULTIPLIER: 100,
    PHASE_THRESHOLDS: [0.66, 0.33],
};

export const SCORING = {
    BASIC_KILL: 100,
    ELITE_KILL: 250,
    BOSS_KILL_BASE: 1000,
    BOSS_KILL_WAVE_BONUS: 200,
    PERFECT_WAVE: 500,
    POWERUP_COLLECT: 50,
    MINE_DESTROY: 150,
    SURVIVAL_PER_SECOND: 10,
    ACCURACY_MIN_MULTIPLIER: 0.5,
    ACCURACY_MAX_MULTIPLIER: 1.5,
};

export const POWERUPS = {
    DROP_CHANCE: 0.15,
    RAPID_FIRE_DURATION: 8000,
    SPREAD_SHOT_DURATION: 8000,
    MISSILE_DURATION: 6000,
    SCORE_MULTI_DURATION: 10000,
};
