export const WAVE_DEFINITIONS = [
  {
    wave: 1,
    enemies: [
      {
        type: "enemy_01",
        enemyType: "grunt",
        pattern: "straight",
        count: 4,
        hp: 1,
        speed: 120,
        fireRate: 3000,
      },
    ],
  },
  {
    wave: 2,
    enemies: [
      {
        type: "enemy_01",
        enemyType: "grunt",
        pattern: "straight",
        count: 5,
        hp: 1,
        speed: 130,
        fireRate: 2800,
      },
      {
        type: "enemy_02",
        enemyType: "grunt",
        pattern: "straight",
        count: 2,
        hp: 1,
        speed: 125,
        fireRate: 2900,
      },
    ],
  },
  {
    wave: 3,
    enemies: [
      {
        type: "enemy_01",
        enemyType: "grunt",
        pattern: "straight",
        count: 6,
        hp: 1,
        speed: 140,
        fireRate: 2600,
      },
      {
        type: "enemy_02",
        enemyType: "grunt",
        pattern: "formation",
        count: 4,
        hp: 1,
        speed: 120,
        fireRate: 2800,
      },
    ],
  },
  {
    wave: 4,
    enemies: [
      {
        type: "enemy_01",
        enemyType: "grunt",
        pattern: "straight",
        count: 4,
        hp: 1,
        speed: 140,
        fireRate: 2500,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 3,
        hp: 2,
        speed: 130,
        fireRate: 2500,
        tint: 0x00ffff,
      },
    ],
  },
  {
    wave: 5,
    enemies: [
      {
        type: "enemy_02",
        enemyType: "grunt",
        pattern: "straight",
        count: 5,
        hp: 1,
        speed: 150,
        fireRate: 2400,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 4,
        hp: 2,
        speed: 140,
        fireRate: 2300,
        tint: 0x00ffff,
      },
    ],
  },
  {
    wave: 6,
    enemies: [
      {
        type: "enemy_02",
        enemyType: "grunt",
        pattern: "formation",
        count: 6,
        hp: 1,
        speed: 150,
        fireRate: 2200,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 5,
        hp: 2,
        speed: 145,
        fireRate: 2200,
        tint: 0x00ffff,
      },
    ],
  },
  {
    wave: 7,
    enemies: [
      {
        type: "enemy_02",
        enemyType: "grunt",
        pattern: "straight",
        count: 4,
        hp: 1,
        speed: 155,
        fireRate: 2200,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 3,
        hp: 2,
        speed: 150,
        fireRate: 2000,
        tint: 0x00ffff,
      },
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 2,
        hp: 2,
        speed: 200,
        fireRate: 9999,
        tint: 0xff4444,
      },
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 2,
        hp: 3,
        speed: 100,
        fireRate: 2000,
        tint: 0xffff00,
      },
    ],
  },
  {
    wave: 8,
    enemies: [
      {
        type: "enemy_02",
        enemyType: "grunt",
        pattern: "straight",
        count: 4,
        hp: 1,
        speed: 160,
        fireRate: 2100,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 3,
        hp: 2,
        speed: 155,
        fireRate: 1900,
        tint: 0x00ffff,
      },
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 3,
        hp: 2,
        speed: 210,
        fireRate: 9999,
        tint: 0xff4444,
      },
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 2,
        hp: 3,
        speed: 110,
        fireRate: 1900,
        tint: 0xffff00,
      },
    ],
  },
  {
    wave: 9,
    enemies: [
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 4,
        hp: 3,
        speed: 120,
        fireRate: 1800,
        tint: 0xffff00,
      },
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 5,
        hp: 2,
        speed: 220,
        fireRate: 9999,
        tint: 0xff4444,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 3,
        hp: 2,
        speed: 160,
        fireRate: 1900,
        tint: 0x00ffff,
      },
    ],
  },
  { wave: 10, boss: "boss_aax", bossHP: 600, enemies: [] },
  {
    wave: 11,
    mines: 2,
    enemies: [
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 3,
        hp: 3,
        speed: 160,
        fireRate: 1700,
        tint: 0xffff00,
      },
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 4,
        hp: 2,
        speed: 230,
        fireRate: 9999,
        tint: 0xff4444,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 4,
        hp: 2,
        speed: 165,
        fireRate: 1800,
        tint: 0x00ffff,
      },
    ],
  },
  {
    wave: 12,
    mines: 3,
    enemies: [
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 5,
        hp: 3,
        speed: 240,
        fireRate: 9999,
        tint: 0xff4444,
      },
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 4,
        hp: 4,
        speed: 170,
        fireRate: 1600,
        tint: 0xffff00,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 3,
        hp: 2,
        speed: 170,
        fireRate: 1700,
        tint: 0x00ffff,
      },
    ],
  },
  {
    wave: 13,
    mines: 3,
    enemies: [
      {
        type: "enemy_01",
        enemyType: "grunt",
        pattern: "straight",
        count: 4,
        hp: 2,
        speed: 180,
        fireRate: 1800,
      },
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 5,
        hp: 3,
        speed: 250,
        fireRate: 9999,
        tint: 0xff4444,
      },
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 3,
        hp: 4,
        speed: 180,
        fireRate: 1500,
        tint: 0xffff00,
      },
      {
        type: "enemy_03",
        enemyType: "zigzagger",
        pattern: "zigzag",
        count: 4,
        hp: 3,
        speed: 175,
        fireRate: 1600,
        tint: 0x00ffff,
      },
    ],
  },
  {
    wave: 14,
    mines: 4,
    enemies: [
      {
        type: "enemy_05",
        enemyType: "formation_leader",
        pattern: "arc",
        count: 6,
        hp: 4,
        speed: 190,
        fireRate: 1400,
        tint: 0xffff00,
      },
      {
        type: "enemy_04",
        enemyType: "diver",
        pattern: "diver",
        count: 6,
        hp: 3,
        speed: 260,
        fireRate: 9999,
        tint: 0xff4444,
      },
    ],
  },
  { wave: 15, boss: "boss_aax", bossHP: 900, enemies: [] },
];

export function generateEscalationWave(waveNum) {
  const scale = 1 + (waveNum - 15) * 0.1;
  const mineCount = Math.min(2 + Math.floor((waveNum - 15) / 2), 8);
  const typeDefs = [
    { type: "enemy_01", enemyType: "grunt", pattern: "straight", tint: null },
    {
      type: "enemy_03",
      enemyType: "zigzagger",
      pattern: "zigzag",
      tint: 0x00ffff,
    },
    { type: "enemy_04", enemyType: "diver", pattern: "diver", tint: 0xff4444 },
    {
      type: "enemy_05",
      enemyType: "formation_leader",
      pattern: "arc",
      tint: 0xffff00,
    },
  ];
  const t1 = typeDefs[(waveNum - 1) % typeDefs.length];
  const t2 = typeDefs[waveNum % typeDefs.length];
  return {
    wave: waveNum,
    mines: mineCount,
    enemies: [
      {
        ...t1,
        count: 4 + Math.floor((waveNum - 15) * 0.5),
        hp: Math.min(2 + Math.floor((waveNum - 15) / 3), 6),
        speed: Math.floor(200 * scale),
        fireRate:
          t1.enemyType === "diver"
            ? 9999
            : Math.max(600, Math.floor(1400 / scale)),
      },
      {
        ...t2,
        count: 3 + Math.floor((waveNum - 15) * 0.4),
        hp: Math.min(2 + Math.floor((waveNum - 15) / 4), 5),
        speed: Math.floor(180 * scale),
        fireRate:
          t2.enemyType === "diver"
            ? 9999
            : Math.max(700, Math.floor(1500 / scale)),
      },
    ],
    ...(waveNum % 5 === 0
      ? { boss: "boss_aax", bossHP: 600 + waveNum * 40 }
      : {}),
  };
}
